
spring:
  application:
    name: cache-service
  output:
    ansi:
      enabled: always
  main:
    allow-bean-definition-overriding: true

cache:
  implementation: hashmap
  props: "cache.properties"
  etcd:
  - http://localhost:2379
